---
- hosts: vmguests
  gather_facts: no
  tasks:
  - name: Check for WinRM connectivity.
    wait_for_connection:

  - name: Join the VMs to the domain.
    win_domain_membership:
      dns_domain_name: acme.epic
      hostname: "{{ inventory_hostname }}"
      domain_admin_user: "{{ ad_domain_user }}"
      domain_admin_password: "{{ ad_domain_pw }}"
      domain_ou_path: "{{ ad_ou_path }}"
      state: domain
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required

